// Flavor text for buildings, techs, and upgrades — ported from legacy en.json
// Purely cosmetic lore/jokes shown in the inspector panel.

export const BUILDING_FLAVOR: Record<string, string> = {
  field: "'Nip as far as the eye can see.",
  pasture: "Take a pint o' milk, Sir!",
  aqueduct: "No Swimming",
  hut: "The Nation of Two",
  logHouse: "The Cabin in the Woods",
  mansion: "The best shipping container available",
  library: "All in Catonese",
  academy: "Curiosity is the basis of science. Our cats died nobly",
  mine: "100 days without diggor mortis",
  barn: "Rats ain't a problem for us!",
  warehouse: "All our stocks are scratched",
  amphitheatre: "Daily 'All Dogs Go to Heaven' showings",
  brewery: "Sir! Want some nip' in ya milk?",
  lumberMill: "Best log analysing tool",
  smelter: "Watch your whiskers!",
  observatory: "Yearning to one day catch the red light fairy",
  workshop: "Free toys for workers",
  steamworks: "I just nap here and it looks like I'm working",
  temple: "All praise Ceiling Cat!",
  unicornPasture: "We glue horns on horses",
  tradepost: "I hope they have yarn",
  harbor: "Ahoy, landlubbers!",
  quarry: "It's full of mice! Wait, wrong 'quarry'",
  oilWell: "Rise early, work hard, strike oil.",
  reactor: "Glowing mice are much easier to catch!",
  biolab: "New postdoc positions available.",
  accelerator: "Large Catron Collider",
  aiCore: "I think we can purr our differences behind us. For science.",
  spaceport: "I want the fancy yarn imported from Yarn.",
};

export const TECH_FLAVOR: Record<string, string> = {
  calendar: "What day is it again?",
  agriculture: "Best thing since sliced bread!",
  archery: "TBD",
  mining: "Pickaxes are easier to hold with opposable thumbs",
  math: "Purr equals Meow times Paw to the square",
  construction: "Making pillow forts smart!",
  civil: "Specialists in Herding Cats",
  writing: "Writing uses less ink than pawprints",
  philosophy: "I purr, therefore I am",
  theology: "What is that flaming ball in the sky anyway?",
  electricity: "Who knew running around on the carpet could generate such power?",
  biology: "The secrets of evolution are time and death",
  biochemistry: "Some of the things that molecules do.",
  genetics: "There's an unbroken thread that stretches from those first cats to us.",
  architecture: "Bigger, better cat towers!",
  archeology: "Different fossils of giant lizards were discovered. Apparently they all died in a sudden but inevitable betrayal.",
  artificialGravity: "The Expawse",
  sattelites: "Spreading cat videos at the speed of light",
};

export const UPGRADE_FLAVOR: Record<string, string> = {
  advancedRefinement: "It's all fun and games 'til someone gets pounced",
  bolas: "Weaponized yarn",
  caravanserai: "Now hiring: cuter kittens",
  cargoShips: "It's like a tuna can, but bigger",
  coalFurnace: "So warm... so sleepy...",
  combustionEngine: "A better mousetrap",
  deepMining: "Yummy Canaries!",
  factoryAutomation: "Includes autofeeders",
  geodesy: "Gold sniffing cats",
  goldOre: "Shiny!",
  huntingArmor: "At least they are wearing something...",
  longRangeSpaceships: "A New Frontier",
  offsetPress: "Paper goes in, cat pictures come out.",
  railgun: "Mice beware",
  silos: "With carpeting and climbing holds of course",
  spiceNavigation: "A curious melange",
  tachyonModerator: "It's also capable of automatically synchronizing cardinal grammeters.",
  titaniumMirrors: "Did that light spot just move?",
};

export const CRAFT_FLAVOR: Record<string, string> = {
  wood: "Scratch-tested, paw-approved",
  beam: "Load-bearing napping platforms",
  slab: "Purrfectly flat",
  plate: "Shiny enough to see your whiskers",
  steel: "Tempered with kitten determination",
  alloy: "The cat's meow of metallurgy",
  scaffold: "For reaching the highest shelves",
  ship: "S.S. Yarn Ball",
  tanker: "Holds 10,000 gallons of milk",
  kerosene: "Rocket fuel for rocket cats",
  parchment: "Made from the finest scratching posts",
  manuscript: "Mostly cat poetry",
  compendium: "The definitive guide to napping",
  blueprint: "Drawn entirely in crayon",
};

export const JOB_FLAVOR: Record<string, string> = {
  hunter: "We're so cute we purr at our prey until it dies",
  miner: "I don't really understand how can I hold a pick with my paws",
  woodcutter: "Must. Not. Scratch.",
};

export const POLICY_FLAVOR: Record<string, string> = {
  liberty: "Every kitten is free to knock things off tables",
  tradition: "We've always done it this way, and we always will",
  monarchy: "One kitten to rule them all",
  authocracy: "The strong paw leads",
  republic: "Of the kittens, by the kittens, for the kittens",
  communism: "From each according to their ability, to each according to their naps",
  fascism: "Order through strength",
  liberalism: "Free markets, free yarn",
  theocracy: "Ceiling Cat wills it",
  technocracy: "Science above all",
  expansionism: "New lands, new scratching posts",
  necrocracy: "Even dead kittens get a vote",
  transkittenism: "Beyond the limits of fur and whiskers",
  radicalXenophobia: "Stranger danger!",
  socialism: "Share the catnip equally",
  diplomacy: "Purrlomacy is the art of letting someone else have your way",
  isolationism: "We have everything we need right here",
  militarism: "Si vis pacem, para bellum",
  mysticism: "The universe is full of magical things patiently waiting for our whiskers to grow sharper",
  carnivale: "Every day is Caturday!",
  stoicism: "A kitten's worth is measured by their naps, not their meows",
  epicurianism: "Eat, drink, and be furry",
  rationing: "One fish, two fish, no more fish",
};

/** Split camelCase to Title Case: "unicornConspiracy" → "Unicorn Conspiracy" */
export function prettifyName(name: string): string {
  return name
    .replace(/([A-Z])/g, " $1")
    .replace(/^./, (c) => c.toUpperCase())
    .trim();
}

export const ACHIEVEMENT_FLAVOR: Record<string, string> = {
  unicornConspiracy: "First unicorn obtained. The cult of the horn begins.",
  uniception: "Tears of unicorns harvested. Empathy not included.",
  sinsOfEmpire: "Alicorns crystallised — the dark side of the cute side.",
  anachronox: "Time crystals farmed. Tomorrow is so yesterday.",
  deadSpace: "Antimatter stockpiled. Don't think too hard about it.",
  sadnessAbyss: "Sorrow has reached unhealthy levels. Bring tea.",
  ironWill: "Survived the no-kittens challenge. Lonely but mighty.",
  uberkatzhen: "Population beyond reasonable cat-care ratios.",
  hundredYearsSolitude: "A hundred in-game years lived. The legacy grows.",
  soilUptuned: "Catnip-field saturation has reshaped the landscape.",
  atlasUnmeowed: "Multiple paragons of progress carry the world on their shoulders.",
  meowMeowRevolution: "Society restructured under a new policy.",
  spaceOddity: "First spacecraft launched. Major Tom would approve.",
  jupiterAscending: "Jupiter colony established. The gas giant smells.",
  veryLargeArray: "Telescope arrays scan the void for whisker signals.",
  shadowOfTheColossus: "Massive structures dot the horizon now.",
  sunGod: "Solar revolutions complete. The sky knows your name.",
  heartOfDarkness: "Necrocorns generated. Probably shouldn't have done that.",
  winterIsComing: "Survived a long winter. Knit a sweater.",
  youMonster: "Sacrificed too many kittens to the cause. Reflection recommended.",
  superUnethicalClimax: "Crossed a line you didn't know was there.",
  systemShock: "Singularity reached. The machine purrs.",
  lotusMachine: "Cryochamber engaged. Time loses meaning.",
  serenity: "Peace through repetition. Inner calm achieved.",
  utopiaProject: "The vision of paradise nears completion.",
  deathStranding: "Connections forged across the void.",
  cathammer: "Forged in iron, sharpened in coal.",
  eternalBacchanalia: "Festival never ends. Hangover not included.",
  challenger: "Completed a challenge run. Hard mode survivor.",
  lotus: "Long meditation rewarded. Patience is power.",
  ivoryTower: "Knowledge stacked high above the masses.",
  useless: "Achievement requirements: do absolutely nothing.",
  beta: "Early adopter. Wore the test fur.",
  silentHill: "Foggy decisions, lasting consequences.",
  evergreen: "Multiple resets, each faster than the last.",
  reginaNoctis: "Queen of the long night.",
  ghostInTheMachine: "AI core hums with feline consciousness.",
  abOwo: "Cute trait spotted. UwU detected.",
  cleanPaws: "No unethical actions taken. Saint mode.",
  sequenceBreak: "Achieved a goal out of order. Speedrunner.",
  fantasticFurColor: "Rare coat genetics emerged.",
  whatYearIsIt: "Time drift detected. The calendar is confused.",
  tardis: "Bigger on the inside.",
  wheredThisComeFrom: "Resource appeared unexpectedly. Carry on.",
  lostDates: "Important events fell off the calendar.",
  buffet: "Stockpiles overflowing. Eat well.",
  newHome: "First hut raised. Welcome home.",
  betterSafeThanSorry: "Storage built before crisis hit. Wise.",
};

export const BADGE_FLAVOR: Record<string, string> = {
  earlyBird: "Reached a milestone fast.",
  speedrunner: "Even faster than that.",
  efficient: "Did more with less.",
  pacifist: "No hunts, no embassies, just vibes.",
  warmonger: "Hunts and embassies in abundance.",
};

export const PERK_FLAVOR: Record<string, string> = {
  engeneering: "Better blueprints, better naps",
  codexVox: "The voice of the ancients, transcribed in paw prints",
  codexLogos: "Logic is just organized curiosity",
  codexAgrum: "Farming wisdom passed down through generations",
  megalomania: "Think big, build bigger",
  goldenRatio: "1.618... the purrfect number",
  vitruvpiawan: "The ideal kitten, measured and drawn",
  diplomacy: "Speak softly and carry a big fish",
  zepibraDiplomacy: "Stripes and spots can get along",
  chronomancy: "Time is just another ball of yarn to unravel",
  unicornmancy: "Horns are just misunderstood",
  carpientry: "Measure twice, scratch once",
  numerology: "Numbers don't lie, but they do purr",
  numeromancy: "Advanced number magic",
  malkpiuth: "The kingdom of earthly delights",
  renaissance: "A golden age of art and science",
  voidOrder: "Stare into the void, and the void purrs back",
  anapichronism: "Yesterday's tomorrow, today",
  pawgan: "Ancient paw rituals",
  adjustmentBureau: "Fine-tuning reality, one whisker at a time",
};
