// Flavor text for buildings, techs, and upgrades — ported from legacy en.json
// Purely cosmetic lore/jokes shown in the inspector panel.

export const BUILDING_FLAVOR: Record<string, string> = {
  field: "'Nip as far as the eye can see.",
  pasture: "Take a pint o' milk, Sir!",
  aqueduct: "No Swimming",
  hut: "The Nation of Two",
  logHouse: "The Cabin in the Woods",
  mansion: "The best shipping container available",
  library: "All in Catonese",
  academy: "Curiosity is the basis of science. Our cats died nobly",
  mine: "100 days without diggor mortis",
  barn: "Rats ain't a problem for us!",
  warehouse: "All our stocks are scratched",
  amphitheatre: "Daily 'All Dogs Go to Heaven' showings",
  brewery: "Sir! Want some nip' in ya milk?",
  lumberMill: "Best log analysing tool",
  smelter: "Watch your whiskers!",
  observatory: "Yearning to one day catch the red light fairy",
  workshop: "Free toys for workers",
  steamworks: "I just nap here and it looks like I'm working",
  temple: "All praise Ceiling Cat!",
  unicornPasture: "We glue horns on horses",
  tradepost: "I hope they have yarn",
  harbor: "Ahoy, landlubbers!",
  quarry: "It's full of mice! Wait, wrong 'quarry'",
  oilWell: "Rise early, work hard, strike oil.",
  reactor: "Glowing mice are much easier to catch!",
  biolab: "New postdoc positions available.",
  accelerator: "Large Catron Collider",
  aiCore: "I think we can purr our differences behind us. For science.",
  spaceport: "I want the fancy yarn imported from Yarn.",
};

export const TECH_FLAVOR: Record<string, string> = {
  calendar: "What day is it again?",
  agriculture: "Best thing since sliced bread!",
  archery: "TBD",
  mining: "Pickaxes are easier to hold with opposable thumbs",
  math: "Purr equals Meow times Paw to the square",
  construction: "Making pillow forts smart!",
  civil: "Specialists in Herding Cats",
  writing: "Writing uses less ink than pawprints",
  philosophy: "I purr, therefore I am",
  theology: "What is that flaming ball in the sky anyway?",
  electricity: "Who knew running around on the carpet could generate such power?",
  biology: "The secrets of evolution are time and death",
  biochemistry: "Some of the things that molecules do.",
  genetics: "There's an unbroken thread that stretches from those first cats to us.",
  architecture: "Bigger, better cat towers!",
  archeology: "Different fossils of giant lizards were discovered. Apparently they all died in a sudden but inevitable betrayal.",
  artificialGravity: "The Expawse",
  sattelites: "Spreading cat videos at the speed of light",
};

export const UPGRADE_FLAVOR: Record<string, string> = {
  advancedRefinement: "It's all fun and games 'til someone gets pounced",
  bolas: "Weaponized yarn",
  caravanserai: "Now hiring: cuter kittens",
  cargoShips: "It's like a tuna can, but bigger",
  coalFurnace: "So warm... so sleepy...",
  combustionEngine: "A better mousetrap",
  deepMining: "Yummy Canaries!",
  factoryAutomation: "Includes autofeeders",
  geodesy: "Gold sniffing cats",
  goldOre: "Shiny!",
  huntingArmor: "At least they are wearing something...",
  longRangeSpaceships: "A New Frontier",
  offsetPress: "Paper goes in, cat pictures come out.",
  railgun: "Mice beware",
  silos: "With carpeting and climbing holds of course",
  spiceNavigation: "A curious melange",
  tachyonModerator: "It's also capable of automatically synchronizing cardinal grammeters.",
  titaniumMirrors: "Did that light spot just move?",
};

export const CRAFT_FLAVOR: Record<string, string> = {
  wood: "Scratch-tested, paw-approved",
  beam: "Load-bearing napping platforms",
  slab: "Purrfectly flat",
  plate: "Shiny enough to see your whiskers",
  steel: "Tempered with kitten determination",
  alloy: "The cat's meow of metallurgy",
  scaffold: "For reaching the highest shelves",
  ship: "S.S. Yarn Ball",
  tanker: "Holds 10,000 gallons of milk",
  kerosene: "Rocket fuel for rocket cats",
  parchment: "Made from the finest scratching posts",
  manuscript: "Mostly cat poetry",
  compendium: "The definitive guide to napping",
  blueprint: "Drawn entirely in crayon",
};

export const JOB_FLAVOR: Record<string, string> = {
  hunter: "We're so cute we purr at our prey until it dies",
  miner: "I don't really understand how can I hold a pick with my paws",
  woodcutter: "Must. Not. Scratch.",
};
